name: yamllint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  # Needed to check out the repo.
  contents: read

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - env:
          YAMLLINT_VERSION: "1.26.3"
        run: |
          set -euo pipefail

          # Install yamllint
          pip install "yamllint==${YAMLLINT_VERSION}"

          # Run yamllint
          make yamllint
